language: cpp
compiler:
  - gcc
cache:
  - apt: true
before_install:
    - sudo apt-get install libwxgtk3.0-dev cmake gcc
before_script:
  - travis_retry cmake .
notifications:
  recipients:
    - milan.dunghubel@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
  - osx
